# Netlify Configuration
[build]
  command = "pnpm install && pnpm build"
  publish = ".next"

[build.environment]
  NODE_VERSION = "18"
  PNPM_VERSION = "8"
  NEXT_TELEMETRY_DISABLED = "1"
  ESLint_NO_DEV_ERRORS = "true"

[[redirects]]
  from = "/pdf"
  to = "/404"
  status = 404
  
[[redirects]]
  from = "/accounting/cash-control/pdf"
  to = "/404"
  status = 404
